# Generated by Django 3.2.17 on 2023-02-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_date', models.DateField(verbose_name='订单日期')),
                ('sj_name', models.CharField(max_length=100, verbose_name='收件姓名')),
                ('sj_mobile', models.CharField(max_length=100, verbose_name='收件电话')),
                ('sj_address', models.CharField(max_length=500, verbose_name='收件地址')),
                ('product_name', models.CharField(max_length=250, verbose_name='商品名称')),
                ('order_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('price', models.FloatField(verbose_name='价格')),
                ('payment_method', models.CharField(max_length=100, verbose_name='付款方式')),
                ('jf_date', models.DateField(verbose_name='进粉日期')),
                ('jz_name', models.CharField(max_length=100, verbose_name='金主姓名')),
                ('remarks', models.CharField(max_length=500, verbose_name='八字/供灯/排位/发会/财库')),
                ('write_state', models.CharField(choices=[('已书写', '已书写'), ('未书写', '未书写')], max_length=100, verbose_name='书写状态')),
                ('kg_date', models.DateField(verbose_name='开光日期')),
                ('sy_remark', models.CharField(max_length=500, verbose_name='寺院备注')),
                ('fh_remark', models.CharField(max_length=500, verbose_name='发货备注')),
                ('service_name', models.CharField(max_length=100, verbose_name='客服姓名')),
                ('fh_data', models.DateField(verbose_name='发货日期')),
                ('courier_number', models.CharField(max_length=100, verbose_name='快递单号')),
                ('shipping_status', models.CharField(choices=[('已发货', '已发货'), ('未发货', '未发货')], default='未发货', max_length=100, verbose_name='发货状态')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('else_one', models.CharField(max_length=100, verbose_name='其他1')),
                ('else_two', models.CharField(max_length=250, verbose_name='其他2')),
                ('else_three', models.CharField(max_length=500, verbose_name='其他3')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicweb.company', verbose_name='部门')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basicweb.position', verbose_name='岗位')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
                'db_table': 'jzt_data',
                'managed': True,
            },
        ),
    ]
